project_name: jx-release-version

release:
  github:
    owner: jenkins-x
    name: jx-release-version

builds:
  - main : main.go
    binary: jx-release-version
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: -X main.Version={{.Version}} -X main.GitTag={{.Tag}} -X main.BuildDate={{.Date}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0

archive:
  files:
    - README.md
    - LICENSE
